routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
	'register' => false,
	'reset' => false
]);

// API with session
Route::get('launch', [App\Http\Controllers\APIController::class, 'launch'])->name('launch');
//

Route::get('redirect/{gameId}/{accountCode}', [App\Http\Controllers\APIController::class, 'redirect'])->name('redirect');

Route::post('commit', [App\Http\Controllers\User\HomeController::class, 'commit'])->name('commit');
	
Route::get('/', [App\Http\Controllers\PublicController::class, 'index'])->name('landing');

Route::get('lobby', [App\Http\Controllers\User\HomeController::class, 'lobby'])->name('lobby');

Route::post('status', [App\Http\Controllers\User\HomeController::class, 'get'])->name('status');

Route::get('result/{id}', [App\Http\Controllers\User\BettingResultController::class, 'index'])->name('result');

Route::post('result/{id}', [App\Http\Controllers\User\BettingResultController::class, 'result']);

// Route::get('topup', [App\Http\Controllers\User\TopupController::class, 'index'])->name('topup');

// Route::post('topup', [App\Http\Controllers\User\TopupController::class, 'topup']);

Route::group(['prefix' => 'record'], function() {
	Route::get('betting', [App\Http\Controllers\User\BettingRecordController::class, 'index'])->name('record.betting');

	Route::post('betting', [App\Http\Controllers\User\BettingRecordController::class, 'listing']);

	Route::get('betting/list/{id}', [App\Http\Controllers\User\BettingRecordController::class, 'index4d'])->name('record.betting.list');

	Route::post('betting/list/{id}', [App\Http\Controllers\User\BettingRecordController::class, 'listing4d']);

	Route::get('invitation', [App\Http\Controllers\User\InvitationRecordController::class, 'index'])->name('record.invitation');

	Route::post('invitation', [App\Http\Controllers\User\InvitationRecordController::class, 'listing']);

	Route::get('topup', [App\Http\Controllers\User\TopupRecordController::class, 'index'])->name('record.topup');

	Route::post('topup', [App\Http\Controllers\User\TopupRecordController::class, 'listing']);

	Route::get('withdraw', [App\Http\Controllers\User\WithdrawRecordController::class, 'index'])->name('record.withdraw');

	Route::post('withdraw', [App\Http\Controllers\User\WithdrawRecordController::class, 'listing']);
});

Route::group(['prefix' => 'room'], function() {
	Route::get('{id}', [App\Http\Controllers\User\BettingController::class, 'index'])->name('room');

	Route::post('{id}', [App\Http\Controllers\User\BettingController::class, 'status']);

	Route::post('{id}/bet', [App\Http\Controllers\User\BettingController::class, 'bet'])->name('room.bet');

	Route::post('{id}/bet/4d', [App\Http\Controllers\User\BettingController::class, 'bet4d'])->name('room.bet.4d');

	Route::post('{id}/record', [App\Http\Controllers\User\BettingController::class, 'record'])->name('room.record');

	Route::post('{id}/clear', [App\Http\Controllers\User\BettingController::class, 'clear'])->name('room.clear');

	Route::post('{id}/redpack', [App\Http\Controllers\User\BettingController::class, 'redpack'])->name('room.redpack');

	Route::post('{id}/rebet', [App\Http\Controllers\User\BettingController::class, 'rebet'])->name('room.rebet');

	Route::post('{id}/rebet/last', [App\Http\Controllers\User\BettingController::class, 'rebetLast'])->name('room.rebetLast');
});

Route::post('withdraw', [App\Http\Controllers\User\HomeController::class, 'withdraw'])->name('withdraw');

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function() {	
	Route::get('login', [App\Http\Controllers\Admin\Auth\LoginController::class, 'showLoginForm'])->name('login');
	Route::post('login', [App\Http\Controllers\Admin\Auth\LoginController::class, 'login']);
	Route::post('logout', [App\Http\Controllers\Admin\Auth\LoginController::class, 'logout'])->name('logout');
	
	Route::get('/', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('dashboard');
	
	Route::group(['middleware' => 'role_control'], function() {
		Route::group(['prefix' => 'banner', 'as' => 'banner'], function() {
			Route::get('/', [App\Http\Controllers\Admin\BannerController::class, 'index']);
		
			Route::post('/', [App\Http\Controllers\Admin\BannerController::class, 'listing'])->name(".listing");;
		
			Route::post('create', [App\Http\Controllers\Admin\BannerController::class, 'create'])->name(".create");
		
			Route::post('update', [App\Http\Controllers\Admin\BannerController::class, 'update'])->name(".update");
		
			Route::delete('delete', [App\Http\Controllers\Admin\BannerController::class, 'destroy'])->name(".delete");
		
			Route::post('upload', [App\Http\Controllers\Admin\BannerController::class, 'upload'])->name(".upload");
		});
		
		Route::group(['prefix' => 'betting', 'as' => 'betting'], function() {
			Route::get('/', [App\Http\Controllers\Admin\BettingController::class, 'index']);
		
			Route::post('/', [App\Http\Controllers\Admin\BettingController::class, 'listing'])->name(".listing");;
		
			Route::post('create', [App\Http\Controllers\Admin\BettingController::class, 'create'])->name(".create");
		
			Route::post('update', [App\Http\Controllers\Admin\BettingController::class, 'update'])->name(".update");
		
			Route::delete('delete', [App\Http\Controllers\Admin\BettingController::class, 'destroy'])->name(".delete");
		
			Route::post('random', [App\Http\Controllers\Admin\BettingController::class, 'random'])->name(".random");
		
			Route::post('deliver', [App\Http\Controllers\Admin\BettingController::class, 'deliver'])->name(".deliver");
		
			Route::group(['prefix' => 'record', 'as' => '.record'], function() {
				Route::get('/', [App\Http\Controllers\Admin\BettingRecordController::class, 'index']);

				Route::post('/', [App\Http\Controllers\Admin\BettingRecordController::class, 'listing'])->name(".listing");
				
				Route::group(['prefix' => '4d', 'as' => '.4d'], function() {
					Route::get('/', [App\Http\Controllers\Admin\BettingRecordController::class, 'index4d']);

					Route::post('/', [App\Http\Controllers\Admin\BettingRecordController::class, 'listing4d'])->name(".listing");
				});
			});
		});

		Route::group(['prefix' => 'invitation', 'as' => 'invitation'], function() {
			Route::group(['prefix' => 'record', 'as' => '.record'], function() {
				Route::get('/', [App\Http\Controllers\Admin\InvitationRecordController::class, 'index']);
			
				Route::post('/', [App\Http\Controllers\Admin\InvitationRecordController::class, 'listing'])->name(".listing");
			});
		});
		
		Route::group(['prefix' => 'role', 'as' => 'role'], function() {
			Route::get('/', [App\Http\Controllers\Admin\RoleController::class, 'index']);
		
			Route::post('/', [App\Http\Controllers\Admin\RoleController::class, 'listing'])->name(".listing");;
		
			Route::post('create', [App\Http\Controllers\Admin\RoleController::class, 'create'])->name(".create");
		
			Route::post('update', [App\Http\Controllers\Admin\RoleController::class, 'update'])->name(".update");
		
			Route::delete('delete', [App\Http\Controllers\Admin\RoleController::class, 'destroy'])->name(".delete");
		
			Route::group(['prefix' => 'access', 'as' => '.access'], function() {
				Route::get('/', [App\Http\Controllers\Admin\RoleAccessController::class, 'index']);
			
				Route::post('/', [App\Http\Controllers\Admin\RoleAccessController::class, 'listing'])->name(".listing");;
			
				Route::post('create', [App\Http\Controllers\Admin\RoleAccessController::class, 'create'])->name(".create");
			
				Route::post('update', [App\Http\Controllers\Admin\RoleAccessController::class, 'update'])->name(".update");
			
				Route::delete('delete', [App\Http\Controllers\Admin\RoleAccessController::class, 'destroy'])->name(".delete");
			});
		});
		
		Route::group(['prefix' => 'room', 'as' => 'room'], function() {
			Route::get('/', [App\Http\Controllers\Admin\RoomController::class, 'index']);
		
			Route::post('/', [App\Http\Controllers\Admin\RoomController::class, 'listing'])->name(".listing");
		
			Route::post('create', [App\Http\Controllers\Admin\RoomController::class, 'create'])->name(".create");
		
			Route::post('update', [App\Http\Controllers\Admin\RoomController::class, 'update'])->name(".update");
		
			Route::post('upload', [App\Http\Controllers\Admin\RoomController::class, 'upload'])->name(".upload");
		
			Route::delete('delete', [App\Http\Controllers\Admin\RoomController::class, 'destroy'])->name(".delete");
		
			Route::group(['prefix' => '{id?}', 'as' => '.rate'], function() {
				Route::get('/', [App\Http\Controllers\Admin\RoomRateController::class, 'index']);
			
				Route::post('/', [App\Http\Controllers\Admin\RoomRateController::class, 'listing'])->name(".listing");
			
				Route::post('create', [App\Http\Controllers\Admin\RoomRateController::class, 'create'])->name(".create");
			
				Route::post('update', [App\Http\Controllers\Admin\RoomRateController::class, 'update'])->name(".update");
			
				Route::delete('delete', [App\Http\Controllers\Admin\RoomRateController::class, 'destroy'])->name(".delete");
			});
		});

		Route::group(['prefix' => 'setting', 'as' => 'setting'], function() {			
			Route::get('/', [App\Http\Controllers\Admin\SettingController::class, 'index']);
			
			Route::post('update', [App\Http\Controllers\Admin\SettingController::class, 'update'])->name('.update');
		});
		
		Route::group(['prefix' => 'staff', 'as' => 'staff'], function() {
			Route::get('/', [App\Http\Controllers\Admin\StaffController::class, 'index']);
		
			Route::post('/', [App\Http\Controllers\Admin\StaffController::class, 'listing'])->name(".listing");;
		

resources/views/admins/bettings/listing.blade.php
@extends('admins.layouts.app')

@section('css')
	<style>
		.responsive{
			width: 100%!important;
		}
		
		.background-red {
			color: white;
			background-color: red;
		}
		
		.background-blue {
			color: white;
			background-color: blue;
		}
		
		.background-green {
			color: white;
			background-color: green;
		}
		
		.background-yellow {
			color: white;
			background-color: #ffaf36;
		}
		
		.roulette-result {
			border-radius: 50%;
			height: 35px;
			width: 35px;
			padding: 3px;
			font-size: 12px;
		}
	</style>
@endsection

@section('content')
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-6">
            <h4 class="page-title">彩票</h4>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">看板</a></li>
                    <li class="breadcrumb-item active" aria-current="page">彩票</li>
                </ol>
            </nav>
        </div>
        <div class="col-6">
            <div class="text-right">
                <small>彩票数量</small>
                <h5 id="count" class="text-info">{{ $record_count }}</h5>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row" style="margin-top: 10px; margin-bottom: 10px;">
        <div class="col-md-3">
			<select class="form-control" onchange="changeListingUrl('room_id', this.value, 0)">
				<option value="">全部房间</option>
				@foreach($rooms as $room)
				<option value="{{ $room->id }}" {{ $room_id && $room_id == $room->id ? "selected" : "" }}>{{ $room->name }}</option>
				@endforeach
			</select>
		</div>
	</div>
    <div class="row">
        <div class="col-md-12">
			<table id="table" class="table table-hover display responsive"></table>
		</div>
    </div>
</div>
@endsection

@section('js')
@parent
<script type="text/javascript">
	let interval;
	let dListingUrl = "{{ Route('admin.betting') }}";
	let qsOptions = {};
	const fpcOrders = {!! json_encode($fpc_order) !!};
		
	function convertQueryString() {
		let qs = "";
		Object.keys(qsOptions).forEach((key, index) => {
			qs += (index == 0 ? "?" : "&") + key + "=" + qsOptions[key];
		});
		return qs;
	}	
	function changeListingUrl(field, val, colIndex = -1) {
		qsOptions[field] = val;
		// reload data
		dTable.ajax.url(dListingUrl + convertQueryString()).load();
		if(colIndex > -1) {
			// show hide column
			const column = dTable.column(colIndex);
			 // Toggle the visibility
			column.visible(val ? false : true);
		}
	}
	const dtOpts = {
		listingUrl: dListingUrl,
		createUrl: "{{ Route('admin.betting.create') }}",
		updateUrl: "{{ Route('admin.betting.update') }}",
		deleteUrl: "{{ Route('admin.betting.delete') }}",
		order: [[ 0, "asc" ]],
		serverSide: true,
		processing: true,
		fields: [{
			label: "{{ __('第1颗骰子') }}",
			name: "ball1",
			type: "text",
			fieldInfo: '{{ $dice_min }}-{{ $dice_max }}'
		}, {
			label: "{{ __('第2颗骰子') }}",
			name: "ball2",
			type: "text",
			fieldInfo: '{{ $dice_min }}-{{ $dice_max }}'
		}, {
			label: "{{ __('第3颗骰子') }}",
			name: "ball3",
			type: "text",
			fieldInfo: '{{ $dice_min }}-{{ $dice_max }}'
		}],
		columns: [{
			title: "{{ __('房间') }}",
			data: "room_name",
			defaultContent: "已删除",
		}, {
			title: "{{ __('期') }}",
			data: "version"
		}, {
			title: "{{ __('结果') }}",
			data: "results",
			render: function (data, config, row) {
				if (data.length > 0) {
					switch (row.game_key) {
							case "fpc":
								return data.map(x => {
									const img = document.createElement("img");
									img.src = "{{ asset('images') }}/" + fpcOrders[x.value] + "-01.png";
									img.style.width = "20px";
									return img.outerHTML;
								});
							case "roulette":
								const i = document.createElement("i");
								i.className = "background-" + data[0].roulette_color + " roulette-result";
								i.innerHTML = (data[0].value).toString().padStart(2, "0");
								return i.outerHTML;
							default:
								return data.map(x => x.value).join(", ");
						}
				} else {
					return "未开奖";
				}
			}
		}, {
			title: "{{ __('下注数') }}",
			data: "record_count",
			defaultContent: "-",
		}, {
			title: "{{ __('参与人数') }}",
			data: "unique_user_count",
			defaultContent: "-",
		}, {
			title: "{{ __('下注金额') }}",
			data: "in_sum",
			defaultContent: "<span class='text-success'>0</span>",
			render: function(data) {
				return "<span class='text-success'>" + (data || "0.00") + "</span>";
			}
		}, {
			title: "{{ __('结算金额') }}",
			data: "out_sum",
			defaultContent: "未结算",
			render: function(data, config, row) {
				return row.reward ? "<span class='text-danger'>" + (data || "0.00") + "</span>" : "未结算";
			}
		}, {
			title: "{{ __('结束日期') }}",
			data: "ended_at",
			render: function (data) {
				return data ? new Date(data).toLocaleString() : "";
			}
		}],
		buttons: function(editor) {
			return [{
				extend: "edit",
				editor: editor,
				text: "{{ __('更新') }}"
			}, {
				text: "{{ __('随机生成彩球') }}",
				extend: "selected",
				action: function (e, dt, node, config) {
					const ids = dt.rows({ selected: true }).data().toArray().map(x => x.id);
					if(ids.length > 0) {
						$.ajax({
							url: "{{ route('admin.betting.random') }}",
							data: {
								ids: ids,
							},
							headers: {
								'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
							},
							type: "POST"
						}).done(function(record) {
							dt.ajax.reload(null, false);
						}).fail(function(err) {
							Swal.fire("发生错误", err.responseJSON.message, "error");
						});
					}
				}
			}, {
				text: "{{ __('手动结算') }}",
				extend: "selected",
				action: function (e, dt, node, config) {
					const ids = dt.rows({ selected: true }).data().toArray().map(x => x.id);
					if(ids.length > 0) {
						$.ajax({
							url: "{{ route('admin.betting.deliver') }}",
							data: {
								ids: ids,
							},
							headers: {
								'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
							},
							type: "POST"
						}).done(function(record) {
							dt.ajax.reload(null, false);
						}).fail(function(err) {
							Swal.fire("发生错误", err.responseJSON.message, "error");
						});
					}
				}
			}, {
				text: "{{ __('刷新') }}",
				action: function (e, dt, node, config) {
					dt.ajax.reload(null, false);
				}
			}, {
				text: "{{ __('自动刷新') }}",
				action: function (e, dt, node, config) {
					if(interval) {
						node[0].innerText = "自动刷新";
						clearInterval(interval);
						interval = null;
					} else {
						node[0].innerText = "刷新中";
						interval = setInterval(function() {
							dt.ajax.reload(null, false);
						}, 30000);
					}
				}
			}];
		}
	}
</script>
	<script src="{{ asset('js/dt.js') }}" defer></script>
@endsection